# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bbd97d042b4b01a3dce89c521a3fbaf60f85b5c46c7658bb59244c12935f1d78e65405cb44a49fe3d413c8ec37f69705315614ffcefc06e7901422c68277bb0

test:
  secret_key_base: 4c01956e988d69bca3bf5e332b3f91e789637c76fa92e835092380f40d39e97557a9476e9d988062c7f46f34f825467595c96ce07752db53d15e73b745126da1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
